// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMf-CZQzf2J7iIIuTQ95bVBLiFrBGS9fE',
    appId: '1:869117266277:android:d592bff0ed62fba290398c',
    messagingSenderId: '869117266277',
    projectId: 'projetoacademiatcc-73645',
    storageBucket: 'projetoacademiatcc-73645.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVCzgou8d4xce6ZFSkM9G4I1V4ufDXcV8',
    appId: '1:869117266277:ios:83eb5c1361f5673690398c',
    messagingSenderId: '869117266277',
    projectId: 'projetoacademiatcc-73645',
    storageBucket: 'projetoacademiatcc-73645.firebasestorage.app',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Mmn07lvjj5PweG9rsc-SrrpVxZUPgCY',
    appId: '1:869117266277:web:938b1a14249e947190398c',
    messagingSenderId: '869117266277',
    projectId: 'projetoacademiatcc-73645',
    authDomain: 'projetoacademiatcc-73645.firebaseapp.com',
    storageBucket: 'projetoacademiatcc-73645.firebasestorage.app',
    measurementId: 'G-P52R08M6VW',
  );

}